routes/web.php
<?php

use App\Http\Controllers\Backend\BankDataController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\DataSpasialController;
use App\Http\Controllers\Backend\GenotipeController;
use App\Http\Controllers\Backend\PengarangController;
use App\Http\Controllers\Backend\VirusController;
use App\Http\Controllers\DataWilayahVirusController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');

// Route::get('/sign-in-bank-data', [HomeController::class, 'signIn'])->name('signIn.BankData');

Route::get('/sign-in', [HomeController::class, 'signIn'])->name('signIn');
Route::post('/postSignIn', [HomeController::class, 'postSignIn'])->name('postSignIn');

Route::get('/register-user', [HomeController::class, 'register'])->name('registerUser');
Route::post('/postRegister', [HomeController::class, 'postRegister'])->name('postRegisterUser');

// search data
Route::get('/show', [HomeController::class, 'data'])->name('home.showData');
// detail from show data
Route::get('/detail/{id}', [HomeController::class, 'detail'])->name('home.detail');
Route::get('/detail-fasta/{id}', [HomeController::class, 'detailFasta'])->name('fasta.detail');


Route::get('/getData', [DataWilayahVirusController::class, 'getData'])->name('getData');
Route::get('/kabupaten', [DataWilayahVirusController::class, 'getKabupaten'])->name('getKabupaten');
// filter maps
Route::get('/filter', [HomeController::class, 'filter']);


// Google
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);
// chart visitor
Route::get('/api-visitor', [DashboardController::class, 'getApiVisitor']);
Route::get('/api-jumlah-virus', [DashboardController::class, 'getVirus']);



Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::get('admin-panel', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('bank-data', BankDataController::class);
    Route::resource('data-spasial', DataSpasialController::class);

    Route::resource('pengarang', PengarangController::class);
    Route::prefix('menu')->group(function () {
        Route::resource('virus', VirusController::class);
        Route::resource('genotipe', GenotipeController::class);
    });
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Backend/BankDataController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Genotipe;
use App\Models\Kabupaten;
use App\Models\Pengarang;
use App\Models\Provinsi;
use App\Models\Sampel;
use App\Models\Sitasi;
use App\Models\Virus;
use Illuminate\Http\Request;
use App\Repository\Wilayah;
use Dflydev\DotAccessData\Data;
use Illuminate\Support\Facades\Auth;

class BankDataController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Sitasi::select('*')->join('tb_sampel', 'tb_sampel.id', 'tb_sitasi.id_sampel')->join('tm_pengarang', 'tm_pengarang.id', 'tb_sitasi.id_pengarang')
            ->orderByDesc('tb_sitasi.created_at')->get();
        return view('backend.bank-data.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $virus = Virus::all();
        $provinsi = Provinsi::all();
        $pengarang = Pengarang::all();
        $genotipe = Genotipe::all();
        return view('backend.bank-data.create', compact('virus', 'provinsi', 'pengarang', 'genotipe'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request;
        $request->validate([
            'kode_sampel' => 'required|unique:tb_sampel',
            'judul_artikel' => 'required',
            'id_virus'  => 'required',
            'genotipe' => 'required',
            'data_sekuen' => 'required',
            'nama_pengarang' => 'required',
            'tempat' => 'required',
            'tanggal' => 'required',
            'id_provinsi' => 'required',
            'id_kabupaten' => 'required',
            'nama_gen' => 'required'
        ]);
        try {

            $data_sampel = new Sampel;
            $data_sampel->kode_sampel = $request->get('kode_sampel');
            $data_sampel->id_virus = $request->get('id_virus');
            $data_sampel->id_genotipe = $request->get('genotipe');
            $data_sampel->nama_gen = $request->get('nama_gen');
            $data_sampel->data_sekuen = $request->get('data_sekuen');
            $data_sampel->id_kota = $request->get('id_kabupaten');
            $data_sampel->id_provinsi = $request->get('id_provinsi');
            $data_sampel->tempat = $request->get('tempat');
            $data_sampel->tanggal_pengambilan = $request->get('tanggal') . '-01';
            $data_sampel->id_pengarang = $request->get('nama_pengarang');
            $data_sampel->save();

            $data_sitasi = new Sitasi;
            $data_sitasi->judul_artikel = $request->get('judul_artikel');
            $data_sitasi->id_pengarang = $request->get('nama_pengarang');
            $data_sitasi->id_sampel = $data_sampel->id;
            $data_sitasi->id_user = Auth()->user()->id;
            $data_sitasi->save();

            return redirect()->route('bank-data.index')->withSuccess('Data Berhasil Ditambahkan');
        } catch (\Exception $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        } catch (\Illuminate\Database\QueryException $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // return $id;
        $virus = Virus::all();
        $provinsi = Provinsi::all();
        $pengarang = Pengarang::all();
        $genotipe = Genotipe::all();
        $data = Sitasi::select('*')
            ->join('tb_sampel', 'tb_sampel.id', 'tb_sitasi.id_sampel')
            ->join('tm_pengarang', 'tm_pengarang.id', 'tb_sitasi.id_pengarang')
            ->where('tb_sitasi.id', $id)->first();
        // return $data;
        return view('backend.bank-data.edit', compact('data', 'pengarang', 'genotipe', 'provinsi', 'virus'));
        // return $data;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_sampel' => 'required',
            'judul_artikel' => 'required',
            'id_virus'  => 'required',
            'genotipe' => 'required',
            'data_sekuen' => 'required',
            'nama_pengarang' => 'required',
            'tempat' => 'required',
            'tanggal' => 'required',
            'id_provinsi' => 'required',
            'id_kabupaten' => 'required',
            'nama_gen' => 'required'
        ]);
        // return $request;
        try {

            $data_sampel = new Sampel;
            $data_sampel->kode_sampel = $request->get('kode_sampel');
            $data_sampel->id_virus = $request->get('id_virus');
            $data_sampel->id_genotipe = $request->get('genotipe');
            $data_sampel->nama_gen = $request->get('nama_gen');
            $data_sampel->data_sekuen = $request->get('data_sekuen');
            $data_sampel->id_kota = $request->get('id_kabupaten');
            $data_sampel->id_provinsi = $request->get('id_provinsi');
            $data_sampel->tempat = $request->get('tempat');
            $data_sampel->tanggal_pengambilan = $request->get('tanggal') . '-01';
            $data_sampel->id_pengarang = $request->get('nama_pengarang');
            $data_sampel->update();

            $data_sitasi = new Sitasi;
            $data_sitasi->judul_artikel = $request->get('judul_artikel');
            $data_sitasi->id_pengarang = $request->get('nama_pengarang');
            // $data_sitasi->id_sampel = $data_sampel->id;
            // $data_sitasi->id_user = Auth()->user()->id;
            $data_sitasi->update();
            return redirect()->route('bank-data.index')->withSuccess('Data Berhasil Dirubah');
        } catch (\Exception $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        } catch (\Illuminate\Database\QueryException $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $data = Sitasi::find($id);
            $sampel = Sampel::find($data->id_sampel);
            $data->delete();
            $sampel->delete();
            return redirect()->route('bank-data.index')->withSuccess('Data Berhasil Dihapus');
        } catch (\Exception $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        } catch (\Illuminate\Database\QueryException $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Provinsi;
use App\Models\Sampel;
use App\Models\Virus;
use App\Models\Visitor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use function PHPUnit\Framework\isEmpty;

class DashboardController extends Controller
{

    public function index()
    {
        $virus = Virus::all();
        $provinsi = Provinsi::all();
        return view('backend.dashboard.index', compact('virus', 'provinsi'));
        # code...
    }


    public function getApiVisitor(Request $request)
    {
        $data = Visitor::select(DB::raw('count(*) as total_visitor, MONTH(date) as date'))
            ->groupBy(DB::raw('MONTH(date)'))
            ->whereYear('date', $request->year)->orderBy('date', 'ASC')->get();

        $bulanarr   = array('Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember');
        if (!$data->isEmpty()) {
            for ($i = 0; $i < count($data); $i++) {
                $arr[0][]  = $bulanarr[$data[$i]['date'] - 1];
                $arr[1][] = $data[$i]['total_visitor'];
            }
            return  $arr;
        } else {
            return 'empty';
        }
    }

    public function getVirus(Request $request)
    {
        if ($request->virus != null) {
            $data = Sampel::select(DB::raw('count(id_virus) as total_virus ,nama_virus'))
                ->where('tanggal_pengambilan', date('Y-m-d', strtotime("01-" . $request->date)))
                ->where('id_virus', $request->virus)
                ->where('id_provinsi', $request->provinsi)
                ->join('tm_virus', 'tm_virus.id', 'tb_sampel.id_virus')
                ->groupBy('nama_virus')
                ->get();
        } else {
            $data = Sampel::select(DB::raw('count(id_virus) as total_virus ,nama_virus'))
                ->join('tm_virus', 'tm_virus.id', 'tb_sampel.id_virus')
                ->groupBy('nama_virus')
                ->get();
        }
        if (count($data) > 0) {
            foreach ($data as $key => $value) {
                $arr['nama_virus'][] = $value->nama_virus;
                $arr['jumlah'][] = $value->total_virus;
            }
            return $arr;
        } else {
            return 'null';
        }
    }
}

app/Http/Controllers/Backend/DataSpasialController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Sitasi;
use App\Models\Virus;
use Illuminate\Http\Request;

class DataSpasialController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Sitasi::select('*', 'tb_sitasi.id')
            ->join('tb_sampel', 'tb_sampel.id', 'tb_sitasi.id_sampel')
            ->join('tm_pengarang', 'tm_pengarang.id', 'tb_sitasi.id_pengarang')
            ->orderByDesc('tb_sitasi.created_at')
            ->get();
        $virus = Virus::all();
        // return $data;
        return view('backend.data-spatial.index', compact('data', 'virus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/data-spatial/index.blade.php
@extends('template.template')
@section('content')
<style>
    .table {
        table-layout: fixed !important;
        white-space: inherit;
    }

    table td {
        word-wrap: break-word;
        overflow: hidden;
        white-space: inherit !important;
    }

    table th {
        word-wrap: break-word;
        overflow: hidden;
        white-space: inherit !important;
    }

    .loader {
        position: absolute;
        bottom: 12em;
        align-items: center;
        z-index: 99999;
        opacity: 1;
    }
</style>
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="fa fa-globe bg-c-blue"></i>
                <div class="d-inline">
                    <h5>{{ ucwords( Request::segment(1) )}}</h5>
                    <span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class=" breadcrumb breadcrumb-title breadcrumb-padding">
                    <li class="breadcrumb-item">
                        <a href="index.html"><i class="feather icon-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="">{{ ucwords( Request::segment(1) )}}</a> </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="card">
                    <div class="card-header bg-light d-flex justify-content-between">
                        <h4 class="fw-bold">Map</h4>
                        <div class="d-flex justify-content-start">
                            <select name="id_virus" id="id_virus"
                                class="form-control  @error('id_virus') is-invalid @enderror" required>
                                @foreach ($virus as $item)
                                <option value="{{ $item->id }} ">
                                    {{ $item->nama_virus }}</option>
                                @endforeach
                            </select>
                            <input type="text" class="form-control  @error('tanggal') is-invalid @enderror" id="date"
                                name="date" style="padding-right: 2em" value="2017-08" placeholder="Bulan & Tahun"
                                required>
                            <button class="btn btn-primary filter">Filter</button>
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="d-flex justify-content-center">
                            <div class="spinner-border text-warning loader" id="spinner" role="status">
                                {{-- <span class="visually-hidden">Loading...</span> --}}
                            </div>
                        </div>
                        <div id="map">
                        </div>
                    </div>
                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="card">
                    <div class="card-header bg-light">
                        <div class="d-flex justify-content-between">
                            <h4 class="fw-bold">Data Spasial</h4>
                            <a href="{{ route('bank-data.create') }}" class="btn btn-primary"> Tambah Data</a>
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="dt-responsive table-responsive">
                            <table class="table table-striped table-bordered nowrap">
                                <thead>
                                    <tr>
                                        <th style="width: 1%">#</th>
                                        <th style="width: 4%">Kode Sampel</th>
                                        <th style="width: 3% ">Virus</th>
                                        <th style="width: 4%;">Genotipe dan Subtipe</th>
                                        <th style="width: 4%">Bulan/Tahun Sampel</th>
                                        <th style="width: 5%;">Tempat Pengambilan</th>
                                        <th style="width: 5%">Kota Pengambilan</th>
                                        <th style="width: 5%">Provinsi Pengambilan</th>
                                        <th style="width: 5%">Opsi</th>
                                    </tr>
                                </thead>
                                <tfoot align="center">
                                    <tr>
                                        <th style="width: 1%">#</th>
                                        <th style="width: 5%">Kode Sampel</th>
                                        <th style="width: 3% ">Virus</th>
                                        <th style="width: 4%;">Genotipe dan Subtipe</th>
                                        <th style="width: 5%">Bulan/Tahun Sampel</th>
                                        <th style="width: 9%;">Tempat Pengambilan</th>
                                        <th style="width: 5%">Kota Pengambilan</th>
                                        <th style="width: 5%">Provinsi Pengambilan</th>
                                        <th style="width: 5%">Opsi</th>
                                    </tr>
                                </tfoot>
                                <tbody align="center">
                                    @forelse ($data as $item)
                                    @php
                                    $virus =
                                    App\Models\Virus::select('nama_virus')->where('id',$item->id_virus)->pluck('nama_virus')[0];
                                    $genotipe =
                                    App\Models\Genotipe::select('kode_genotipe')->where('id',$item->id_genotipe)->pluck('kode_genotipe')[0];
                                    @endphp
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->kode_sampel }}ds{{ $item->id }}</td>
                                        <td>{{ $virus }}</td>
                                        <td>{{ $genotipe }}</td>
                                        <td>{{ tanggal_indo($item->tanggal_pengambilan) }}</td>
                                        <td>{{ $item->tempat}}</td>
                                        <td>{{ getKota($item->id_kota)}}</td>
                                        <td>{{ getProvinsi($item->id_provinsi) }}</td>
                                        <td>
                                            <div class="d-flex justify-content-start">
                                                <a class="btn btn-primary"
                                                    href="{{ route('bank-data.edit',$item->id) }}"
                                                    style="margin-right: 0.5em"><i
                                                        class="fa fa-pencil text-center m-0"></i>
                                                </a>
                                                <form action="{{ route('bank-data.destroy', $item->id) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit"
                                                        onclick="return confirm('Are you sure you want to delete this item?');"
                                                        class="btn btn-danger"><i
                                                            class="fa fa-trash text-center m-0"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center">Data Masih Belum ada</td>
                                    </tr>
                                    @endforelse
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>
@endsection
@include('backend.data-spatial.leaflet')
@php
function tanggal_indo($tanggal)
{
$bulan = array (1 => 'Januari',
'Februari',
'Maret',
'April',
'Mei',
'Juni',
'Juli',
'Agustus',
'September',
'Oktober',
'November',
'Desember'
);
$split = explode('-', $tanggal);
return $bulan[ (int)$split[1] ] . ' ' . $split[0];
}

function getProvinsi($id)
{
$prov = App\Models\Provinsi::where('id', $id)->pluck('nama_provinsi')[0];
return $prov;
}
function getKota($id)
{
$kab = App\Models\Kabupaten::where('id', $id)->pluck('nama_kabupaten')[0];
return $kab;
}
@endphp
@push('js')


<script>
    $('#date').datepicker({
        autoclose: true,
        viewMode: 'years',
        format: 'yyyy-mm',
        minViewMode: 1,
        zIndexOffset : 99999999,
    });

    $(document).ready(function () {
        $('.table').DataTable({
            "autoWidth": false,
        });
    });

</script>
@endpush