routes/web.php
<?php

use App\Http\Controllers\Backend\BankDataController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\DataSpasialController;
use App\Http\Controllers\Backend\GenotipeController;
use App\Http\Controllers\Backend\PengarangController;
use App\Http\Controllers\Backend\VirusController;
use App\Http\Controllers\DataWilayahVirusController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');

// Route::get('/sign-in-bank-data', [HomeController::class, 'signIn'])->name('signIn.BankData');

Route::get('/sign-in', [HomeController::class, 'signIn'])->name('signIn');
Route::post('/postSignIn', [HomeController::class, 'postSignIn'])->name('postSignIn');

Route::get('/register-user', [HomeController::class, 'register'])->name('registerUser');
Route::post('/postRegister', [HomeController::class, 'postRegister'])->name('postRegisterUser');

// search data
Route::get('/show', [HomeController::class, 'data'])->name('home.showData');
// detail from show data
Route::get('/detail/{id}', [HomeController::class, 'detail'])->name('home.detail');
Route::get('/detail-fasta/{id}', [HomeController::class, 'detailFasta'])->name('fasta.detail');


Route::get('/getData', [DataWilayahVirusController::class, 'getData'])->name('getData');
Route::get('/kabupaten', [DataWilayahVirusController::class, 'getKabupaten'])->name('getKabupaten');
// filter maps
Route::get('/filter', [HomeController::class, 'filter']);


// Google
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);
// chart visitor
Route::get('/api-visitor', [DashboardController::class, 'getApiVisitor']);
Route::get('/api-jumlah-virus', [DashboardController::class, 'getVirus']);



Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::get('admin-panel', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('bank-data', BankDataController::class);
    Route::resource('data-spasial', DataSpasialController::class);

    Route::resource('pengarang', PengarangController::class);
    Route::prefix('menu')->group(function () {
        Route::resource('virus', VirusController::class);
        Route::resource('genotipe', GenotipeController::class);
    });
});

require __DIR__ . '/auth.php';

resources/views/template/partials/alert.blade.php
@push('js')
@if (session('success'))
<script>
    Swal.fire({
        icon: 'success',
        title: 'Sukses',
        text: "{{ session()->get('success') }}",
        showCancelButton: false,
        confirmButtonText: 'OK',
    }).then((result) => {
    /* Read more about isConfirmed, isDenied below */
    if (result.isConfirmed) {
        sessionStorage.removeItem('success');
    }
    })

</script>
@endif
@if (session('info'))
<script>
    Swal.fire({
        icon: 'info',
        title: 'Mohon Maaf',
        text: "{{ session()->get('info') }}",
        type: "info"
    })
</script>
@endif
@if (session('error'))
<script>
    Swal.fire({
        icon: 'error',
        title: 'Terjadi Kesalahan',
        text: "{{ session()->get('error') }}",
        type: "error"
    })
</script>
@endif
@endpush

resources/views/template/partials/head.blade.php
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Quicksand:500,700" rel="stylesheet">
<!-- Required Fremwork -->
<link rel="stylesheet" type="text/css" href="{{  asset('bower_components/bootstrap/css/bootstrap.min.css') }}">
<!-- waves.css -->
<link rel="stylesheet" href="{{ asset('assets/pages/waves/css/waves.min.css') }}" type="text/css" media="all">
<!-- feather icon -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/icon/feather/css/feather.css') }}">
<!-- font-awesome-n -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/font-awesome-n.min.css') }}">
<!-- Chartlist chart css -->
<link rel="stylesheet" href="{{ asset('bower_components/chartist/css/chartist.css') }}" type="text/css" media="all">
<!-- Style.css -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }}">
<!--- leaflet --->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
    integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
<!-- Data Table Css -->
<link rel="stylesheet" type="text/css"
    href="{{ asset('bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/pages/data-table/css/buttons.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css"
    href="{{ asset('bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css"
    integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css"
    integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- feather icon -->
<link rel="stylesheet" type="text/css" href="{{   asset('assets/icon/feather/css/feather.css') }}">
<!-- ico font -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/icon/icofont/css/icofont.css') }}">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

@stack('css')

resources/views/template/partials/script.blade.php
<!--- leaflet --->
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
    integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
    integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />

<!-- Required Jquery -->
<script type="text/javascript" src="{{ asset('bower_components/jquery/js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('bower_components/jquery-ui/js/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('bower_components/popper.js/js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('bower_components/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- waves js -->
<script src="{{ asset('assets/pages/waves/js/waves.min.js') }}"></script>
<!-- jquery slimscroll js -->
<script type="text/javascript" src="{{ asset('bower_components/jquery-slimscroll/js/jquery.slimscroll.js') }}"></script>
<!-- Float Chart js -->
<script src="{{ asset('assets/pages/chart/float/jquery.flot.js') }}"></script>
<script src="{{ asset('assets/pages/chart/float/jquery.flot.categories.js') }}"></script>
<script src="{{ asset('assets/pages/chart/float/curvedLines.js') }}"></script>
<script src="{{ asset('assets/pages/chart/float/jquery.flot.tooltip.min.js') }}"></script>
<!-- Chartlist charts -->
<script src="{{ asset('bower_components/chartist/js/chartist.js') }}"></script>
<!-- amchart js -->
<script src="{{ asset('assets/pages/widget/amchart/amcharts.js') }}"></script>
<script src="{{ asset('assets/pages/widget/amchart/serial.js') }}"></script>
<script src="{{ asset('assets/pages/widget/amchart/light.js') }}"></script>
<!-- Custom js -->
<script src="{{ asset('assets/js/pcoded.min.js') }}"></script>
<script src="{{ asset('assets/js/vertical/vertical-layout.min.js') }}"></script>

<!-- data-table js -->
<script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/pages/data-table/js/jszip.min.js') }}"></script>
<script src="{{ asset('assets/pages/data-table/js/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/pages/data-table/js/vfs_fonts.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
<!-- Custom js -->
{{-- <script src="{{ asset('assets/pages/data-table/js/data-table-custom.js') }}"></script> --}}

{{-- <script type="text/javascript" src="{{ asset('assets/pages/dashboard/custom-dashboard.min.js') }}"></script> --}}
<script type="text/javascript" src="{{ asset('assets/js/script.min.js') }}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>



@stack('js')

resources/views/template/partials/sidebar.blade.php
<nav class="pcoded-navbar">
    <div class="nav-list">
        <div class="pcoded-inner-navbar main-menu">
            <ul class="pcoded-item pcoded-left-item">
                <li class="{{ Request::segment(1) == 'admin-panel' ? 'active' : '' }}">
                    <a href="{{ route('dashboard') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-home"></i>
                        </span>
                        <span class="pcoded-mtext">Dashboard</span>
                    </a>
                </li>
            </ul>
            <div class="pcoded-navigation-label">Master Data</div>
            <ul class="pcoded-item pcoded-left-item">
                <li class="{{ Request::segment(1) == 'bank-data' ? 'active' : '' }}">
                    <a href="{{ route('bank-data.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-folder"></i>
                        </span>
                        <span class="pcoded-mtext">Bank Data</span>
                    </a>
                </li>
                <li class="{{ Request::segment(1) == 'data-spasial' ? 'active' : '' }}">
                    <a href="{{ route('data-spasial.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-globe"></i>
                        </span>
                        <span class="pcoded-mtext">Data Spasial</span>
                    </a>
                </li>
                <li class="{{ Request::segment(1) == 'pengarang' ? 'active' : '' }}">
                    <a href="{{ route('pengarang.index') }}" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="fa fa-clipboard"></i>
                        </span>
                        <span class="pcoded-mtext">Data Penulis</span>
                    </a>
                </li>
                <ul class="pcoded-item pcoded-left-item">
                    <li class="pcoded-hasmenu {{ Request::segment(1) == 'menu' ? 'active pcoded-trigger' : '' }}">
                        <a href="javascript:void(0)" class="waves-effect waves-dark">
                            <span class="pcoded-micon"><i class="feather icon-list"></i></span>
                            <span class="pcoded-mtext">Menu</span>
                        </a>
                        <ul class="pcoded-submenu">
                            <li class="{{ Request::segment(2) == 'virus' ? 'active' : '' }}">
                                <a href="{{ route('virus.index') }}" class="waves-effect waves-dark">
                                    <span class="pcoded-mtext">Virus</span>
                                </a>
                            </li>
                            <li class="{{ Request::segment(2) == 'genotipe' ? 'active' : '' }}">
                                <a href="{{ route('genotipe.index') }}" class="waves-effect waves-dark">
                                    <span class="pcoded-mtext">Genotipe & Subtype</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </ul>
        </div>
    </div>
</nav>