routes/web.php
<?php

use App\Http\Controllers\Backend\BankDataController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\DataSpasialController;
use App\Http\Controllers\Backend\GenotipeController;
use App\Http\Controllers\Backend\PengarangController;
use App\Http\Controllers\Backend\VirusController;
use App\Http\Controllers\DataWilayahVirusController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');

// Route::get('/sign-in-bank-data', [HomeController::class, 'signIn'])->name('signIn.BankData');

Route::get('/sign-in', [HomeController::class, 'signIn'])->name('signIn');
Route::post('/postSignIn', [HomeController::class, 'postSignIn'])->name('postSignIn');

Route::get('/register-user', [HomeController::class, 'register'])->name('registerUser');
Route::post('/postRegister', [HomeController::class, 'postRegister'])->name('postRegisterUser');

// search data
Route::get('/show', [HomeController::class, 'data'])->name('home.showData');
// detail from show data
Route::get('/detail/{id}', [HomeController::class, 'detail'])->name('home.detail');
Route::get('/detail-fasta/{id}', [HomeController::class, 'detailFasta'])->name('fasta.detail');


Route::get('/getData', [DataWilayahVirusController::class, 'getData'])->name('getData');
Route::get('/kabupaten', [DataWilayahVirusController::class, 'getKabupaten'])->name('getKabupaten');
// filter maps
Route::get('/filter', [HomeController::class, 'filter']);


// Google
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);
// chart visitor
Route::get('/api-visitor', [DashboardController::class, 'getApiVisitor']);
Route::get('/api-jumlah-virus', [DashboardController::class, 'getVirus']);



Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::get('admin-panel', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('bank-data', BankDataController::class);
    Route::resource('data-spasial', DataSpasialController::class);

    Route::resource('pengarang', PengarangController::class);
    Route::prefix('menu')->group(function () {
        Route::resource('virus', VirusController::class);
        Route::resource('genotipe', GenotipeController::class);
    });
});

require __DIR__ . '/auth.php';

app/Models/Virus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Virus extends Model
{
    use HasFactory;
    protected $table = 'tm_virus';
}

app/Http/Controllers/Backend/BankDataController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Genotipe;
use App\Models\Kabupaten;
use App\Models\Pengarang;
use App\Models\Provinsi;
use App\Models\Sampel;
use App\Models\Sitasi;
use App\Models\Virus;
use Illuminate\Http\Request;
use App\Repository\Wilayah;
use Dflydev\DotAccessData\Data;
use Illuminate\Support\Facades\Auth;

class BankDataController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Sitasi::select('*')->join('tb_sampel', 'tb_sampel.id', 'tb_sitasi.id_sampel')->join('tm_pengarang', 'tm_pengarang.id', 'tb_sitasi.id_pengarang')
            ->orderByDesc('tb_sitasi.created_at')->get();
        return view('backend.bank-data.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $virus = Virus::all();
        $provinsi = Provinsi::all();
        $pengarang = Pengarang::all();
        $genotipe = Genotipe::all();
        return view('backend.bank-data.create', compact('virus', 'provinsi', 'pengarang', 'genotipe'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request;
        $request->validate([
            'kode_sampel' => 'required|unique:tb_sampel',
            'judul_artikel' => 'required',
            'id_virus'  => 'required',
            'genotipe' => 'required',
            'data_sekuen' => 'required',
            'nama_pengarang' => 'required',
            'tempat' => 'required',
            'tanggal' => 'required',
            'id_provinsi' => 'required',
            'id_kabupaten' => 'required',
            'nama_gen' => 'required'
        ]);
        try {

            $data_sampel = new Sampel;
            $data_sampel->kode_sampel = $request->get('kode_sampel');
            $data_sampel->id_virus = $request->get('id_virus');
            $data_sampel->id_genotipe = $request->get('genotipe');
            $data_sampel->nama_gen = $request->get('nama_gen');
            $data_sampel->data_sekuen = $request->get('data_sekuen');
            $data_sampel->id_kota = $request->get('id_kabupaten');
            $data_sampel->id_provinsi = $request->get('id_provinsi');
            $data_sampel->tempat = $request->get('tempat');
            $data_sampel->tanggal_pengambilan = $request->get('tanggal') . '-01';
            $data_sampel->id_pengarang = $request->get('nama_pengarang');
            $data_sampel->save();

            $data_sitasi = new Sitasi;
            $data_sitasi->judul_artikel = $request->get('judul_artikel');
            $data_sitasi->id_pengarang = $request->get('nama_pengarang');
            $data_sitasi->id_sampel = $data_sampel->id;
            $data_sitasi->id_user = Auth()->user()->id;
            $data_sitasi->save();

            return redirect()->route('bank-data.index')->withSuccess('Data Berhasil Ditambahkan');
        } catch (\Exception $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        } catch (\Illuminate\Database\QueryException $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // return $id;
        $virus = Virus::all();
        $provinsi = Provinsi::all();
        $pengarang = Pengarang::all();
        $genotipe = Genotipe::all();
        $data = Sitasi::select('*')
            ->join('tb_sampel', 'tb_sampel.id', 'tb_sitasi.id_sampel')
            ->join('tm_pengarang', 'tm_pengarang.id', 'tb_sitasi.id_pengarang')
            ->where('tb_sitasi.id', $id)->first();
        // return $data;
        return view('backend.bank-data.edit', compact('data', 'pengarang', 'genotipe', 'provinsi', 'virus'));
        // return $data;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_sampel' => 'required',
            'judul_artikel' => 'required',
            'id_virus'  => 'required',
            'genotipe' => 'required',
            'data_sekuen' => 'required',
            'nama_pengarang' => 'required',
            'tempat' => 'required',
            'tanggal' => 'required',
            'id_provinsi' => 'required',
            'id_kabupaten' => 'required',
            'nama_gen' => 'required'
        ]);
        // return $request;
        try {

            $data_sampel = new Sampel;
            $data_sampel->kode_sampel = $request->get('kode_sampel');
            $data_sampel->id_virus = $request->get('id_virus');
            $data_sampel->id_genotipe = $request->get('genotipe');
            $data_sampel->nama_gen = $request->get('nama_gen');
            $data_sampel->data_sekuen = $request->get('data_sekuen');
            $data_sampel->id_kota = $request->get('id_kabupaten');
            $data_sampel->id_provinsi = $request->get('id_provinsi');
            $data_sampel->tempat = $request->get('tempat');
            $data_sampel->tanggal_pengambilan = $request->get('tanggal') . '-01';
            $data_sampel->id_pengarang = $request->get('nama_pengarang');
            $data_sampel->update();

            $data_sitasi = new Sitasi;
            $data_sitasi->judul_artikel = $request->get('judul_artikel');
            $data_sitasi->id_pengarang = $request->get('nama_pengarang');
            // $data_sitasi->id_sampel = $data_sampel->id;
            // $data_sitasi->id_user = Auth()->user()->id;
            $data_sitasi->update();
            return redirect()->route('bank-data.index')->withSuccess('Data Berhasil Dirubah');
        } catch (\Exception $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        } catch (\Illuminate\Database\QueryException $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $data = Sitasi::find($id);
            $sampel = Sampel::find($data->id_sampel);
            $data->delete();
            $sampel->delete();
            return redirect()->route('bank-data.index')->withSuccess('Data Berhasil Dihapus');
        } catch (\Exception $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        } catch (\Illuminate\Database\QueryException $e) {
            return $e;
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Provinsi;
use App\Models\Sampel;
use App\Models\Virus;
use App\Models\Visitor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use function PHPUnit\Framework\isEmpty;

class DashboardController extends Controller
{

    public function index()
    {
        $virus = Virus::all();
        $provinsi = Provinsi::all();
        return view('backend.dashboard.index', compact('virus', 'provinsi'));
        # code...
    }


    public function getApiVisitor(Request $request)
    {
        $data = Visitor::select(DB::raw('count(*) as total_visitor, MONTH(date) as date'))
            ->groupBy(DB::raw('MONTH(date)'))
            ->whereYear('date', $request->year)->orderBy('date', 'ASC')->get();

        $bulanarr   = array('Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember');
        if (!$data->isEmpty()) {
            for ($i = 0; $i < count($data); $i++) {
                $arr[0][]  = $bulanarr[$data[$i]['date'] - 1];
                $arr[1][] = $data[$i]['total_visitor'];
            }
            return  $arr;
        } else {
            return 'empty';
        }
    }

    public function getVirus(Request $request)
    {
        if ($request->virus != null) {
            $data = Sampel::select(DB::raw('count(id_virus) as total_virus ,nama_virus'))
                ->where('tanggal_pengambilan', date('Y-m-d', strtotime("01-" . $request->date)))
                ->where('id_virus', $request->virus)
                ->where('id_provinsi', $request->provinsi)
                ->join('tm_virus', 'tm_virus.id', 'tb_sampel.id_virus')
                ->groupBy('nama_virus')
                ->get();
        } else {
            $data = Sampel::select(DB::raw('count(id_virus) as total_virus ,nama_virus'))
                ->join('tm_virus', 'tm_virus.id', 'tb_sampel.id_virus')
                ->groupBy('nama_virus')
                ->get();
        }
        if (count($data) > 0) {
            foreach ($data as $key => $value) {
                $arr['nama_virus'][] = $value->nama_virus;
                $arr['jumlah'][] = $value->total_virus;
            }
            return $arr;
        } else {
            return 'null';
        }
    }
}

app/Http/Controllers/Backend/DataSpasialController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Sitasi;
use App\Models\Virus;
use Illuminate\Http\Request;

class DataSpasialController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Sitasi::select('*', 'tb_sitasi.id')
            ->join('tb_sampel', 'tb_sampel.id', 'tb_sitasi.id_sampel')
            ->join('tm_pengarang', 'tm_pengarang.id', 'tb_sitasi.id_pengarang')
            ->orderByDesc('tb_sitasi.created_at')
            ->get();
        $virus = Virus::all();
        // return $data;
        return view('backend.data-spatial.index', compact('data', 'virus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/virus/detail.blade.php
@extends('template.template')
@section('content')
<style>
    .table {
        table-layout: fixed !important;
        white-space: inherit;
    }

    table td {
        word-wrap: break-word;
        overflow: hidden;
        white-space: inherit !important;
    }

    table th {
        word-wrap: break-word;
        overflow: hidden;
        white-space: inherit !important;
    }
</style>
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="fa fa-snowflake bg-c-blue"></i>
                <div class="d-inline">
                    <h5>{{ ucwords( Request::segment(1) )}}</h5>
                    <span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class=" breadcrumb breadcrumb-title breadcrumb-padding">
                    <li class="breadcrumb-item">
                        <a href="index.html"><i class="feather icon-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('virus.index') }}">{{ ucwords( Request::segment(2)
                            )}}</a> </li>
                    <li class="breadcrumb-item"><a href="">Detail Virus</a> </li>

                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->
{{-- <div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="card">
                    <div class="card-header bg-light">
                        <div class="d-flex justify-content-between align-middle">
                            <h6 class="mt-2 fw-bold">{{ $title }}</h6>
                            <button class="btn btn-primary border-none" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                                <i class="fa fa-minus m-0"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-block collapse {{ session()->has('errors') == 1 ? 'show' : '' }}"
                        id="collapseExample">
                        <form action="{{ route('virus.store') }}" method="post">
                            @csrf
                            <div class="row">
                                <div class="col-4 mb-3">
                                    <input type="text" name="nama_virus" id="disabledTextInput" class="form-control @error('nama_virus')
                                    is-invalid @enderror" placeholder="Masukkan Nama Virus">
                                    @error('nama_virus')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="col-4 ">
                                    <button type="submit" class="btn btn-primary">Tambah Data</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div> --}}

<div class="pcoded-inner-content m-0">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="card">
                    <div class="card-header bg-light">
                        <div class="d-flex justify-content-between align-middle">
                            <h6 class="mt-2 fw-bold">{{ $title }} {{ $virus}}</h6>
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="dt-responsive table-responsive">
                            <table class="table table-striped table-bordered nowrap" id="table-virus">
                                <thead>
                                    <tr>
                                        <th style="width: 4%">#</th>
                                        <th style="width: 70%">Genotipe & Subtipe</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($data as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td> <a href="">{{ $item->kode_genotipe }}</a> </td>
                                        {{-- <th>
                                            <div class="d-flex justify-content-start">
                                                <button class="btn btn-primary " style="margin-right: 0.5em"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#exampleModal{{ $item->id }}"><i
                                                        class="fa fa-pencil text-center m-0"></i></button>
                                                <form action="{{  route('virus.destroy',$item->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="sumbit" class="btn btn-danger"><i
                                                            class="fa fa-trash text-center m-0"></i></button>
                                                </form>
                                            </div>
                                        </th> --}}
                                    </tr>
                                    @include('backend.virus.editModal')
                                    @empty
                                    <tr>
                                        <td colspan="3" class="text-center">Data Masih tidak ada</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Genotipe & Subtipe</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>
@endsection
@include('template.partials.alert')
@push('js')
<script>
    $(document).ready(function () {
        $('.table').DataTable({
            "autoWidth": false,
        });
    });
</script>
@endpush

resources/views/backend/virus/editModal.blade.php
<div class="modal fade" id="exampleModal{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('virus.update',$item->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
                </div>
                <div class="modal-body">
                    <div class="col-6 mb-3">
                        <label for="virus" class="form-label">Nama Virus<small class="text-danger"> *</small>
                        </label>
                        <input type="text" name="nama_virus" id="nama_virus" value="{{ $item->nama_virus }}"
                            class="form-control @error('nama_virus') is-invalid @enderror"
                            placeholder="Masukkan Nama Virus">
                        @error('nama_virus')
                        <span class="invalid-feedback message">
                            {{ $message }}
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type=" submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/backend/virus/index.blade.php
@extends('template.template')
@section('content')
<style>
    .table {
        table-layout: fixed !important;
        white-space: inherit;
    }

    table td {
        word-wrap: break-word;
        overflow: hidden;
        white-space: inherit !important;
    }

    table th {
        word-wrap: break-word;
        overflow: hidden;
        white-space: inherit !important;
    }
</style>
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="fa fa-snowflake bg-c-blue"></i>
                <div class="d-inline">
                    <h5>{{ ucwords( Request::segment(2) )}}</h5>
                    <span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class=" breadcrumb breadcrumb-title breadcrumb-padding">
                    <li class="breadcrumb-item">
                        <a href="index.html"><i class="feather icon-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="">{{ ucwords( Request::segment(2) )}}</a> </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="card">
                    <div class="card-header bg-light">
                        <div class="d-flex justify-content-between align-middle">
                            <h6 class="mt-2 fw-bold">Tambah Data Virus</h6>
                            <button class="btn btn-primary border-none" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                                <i class="fa fa-minus m-0"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-block collapse {{ session()->has('errors') == 1 ? 'show' : '' }}"
                        id="collapseExample">
                        <form action="{{ route('virus.store') }}" method="post">
                            @csrf
                            <div class="row">
                                <div class="col-4 mb-3">
                                    <input type="text" name="nama_virus" id="disabledTextInput" class="form-control @error('nama_virus')
                                    is-invalid @enderror" placeholder="Masukkan Nama Virus">
                                    @error('nama_virus')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="col-4 ">
                                    <button type="submit" class="btn btn-primary">Tambah Data</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>

<div class="pcoded-inner-content m-0">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="card">
                    <div class="card-header bg-light">
                        <div class="d-flex justify-content-between align-middle">
                            <h6 class="mt-2 fw-bold">Data Virus</h6>
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="dt-responsive table-responsive">
                            <table class="table table-striped table-bordered nowrap" id="table-virus">
                                <thead>
                                    <tr>
                                        <th style="width: 4%">#</th>
                                        <th style="width: 70%">Nama Virus</th>
                                        <th style="width: 26%">Opsi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($data as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td> <a href="{{ route('virus.show', $item->id) }}">{{ $item->nama_virus }}</a>
                                        </td>
                                        <th>
                                            <div class="d-flex justify-content-start">
                                                <button class="btn btn-primary " style="margin-right: 0.5em"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#exampleModal{{ $item->id }}"><i
                                                        class="fa fa-pencil text-center m-0"></i></button>
                                                <form action="{{  route('virus.destroy',$item->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="sumbit" class="btn btn-danger"
                                                        onclick="return confirm('Are you sure you want to delete this item?');"><i
                                                            class="fa fa-trash text-center m-0"></i></button>
                                                </form>
                                            </div>
                                        </th>
                                    </tr>
                                    @include('backend.virus.editModal')
                                    @empty
                                    <tr>
                                        <td colspan="3" class="text-center">Data Masih tidak ada</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama Virus</th>
                                        <th>Opsi</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>
@endsection
@include('template.partials.alert')
@push('js')
<script>
    $(document).ready(function () {
        $('.table').DataTable({
            "autoWidth": false,
        });
    });
</script>
@endpush